from __future__ import annotations

from .auth import ROLE_ADMIN, ROLE_MANAGER, VALID_ROLES, CrmSession, CrmUser
from .base import Base
from .common import (
    ENTITY_CONTACT,
    ENTITY_DEAL,
    VALID_FIELD_ENTITIES,
    VALID_TAG_ENTITIES,
    CrmActivityLog,
    CrmCustomField,
    CrmEntityTag,
    CrmLostReason,
    CrmSetting,
    CrmTag,
)
from .contacts import CONTACT_SOURCE_BOT, CrmContact, CrmConversationState
from .deals import (
    DEAL_STATUS_LOST,
    DEAL_STATUS_OPEN,
    DEAL_STATUS_WON,
    DEFAULT_CURRENCY,
    HISTORY_SOURCE_BOT,
    HISTORY_SOURCE_MANAGER,
    HISTORY_SOURCE_SYSTEM,
    VALID_DEAL_STATUSES,
    VALID_HISTORY_SOURCES,
    CrmDeal,
    CrmDealStageHistory,
)
from .notes import CrmNote
from .notify import CrmAutomation, CrmNotification
from .pipelines import (
    STAGE_KIND_LOST,
    STAGE_KIND_OPEN,
    STAGE_KIND_WON,
    STATUS_CLIENT,
    STATUS_LOST,
    STATUS_MANAGER,
    VALID_STAGE_KINDS,
    CrmPipeline,
    CrmStage,
)
from .tasks import (
    TASK_TYPE_CALL,
    TASK_TYPE_MEETING,
    TASK_TYPE_MESSAGE,
    TASK_TYPE_OTHER,
    VALID_TASK_TYPES,
    CrmTask,
)
from .views import CrmSavedView

__all__ = [
    "Base",
    "CONTACT_SOURCE_BOT",
    "CrmActivityLog",
    "CrmAutomation",
    "CrmContact",
    "CrmConversationState",
    "CrmCustomField",
    "CrmDeal",
    "CrmDealStageHistory",
    "CrmEntityTag",
    "CrmLostReason",
    "CrmNote",
    "CrmNotification",
    "CrmPipeline",
    "CrmSavedView",
    "CrmSession",
    "CrmSetting",
    "CrmStage",
    "CrmTag",
    "CrmTask",
    "CrmUser",
    "DEAL_STATUS_LOST",
    "DEAL_STATUS_OPEN",
    "DEAL_STATUS_WON",
    "DEFAULT_CURRENCY",
    "ENTITY_CONTACT",
    "ENTITY_DEAL",
    "HISTORY_SOURCE_BOT",
    "HISTORY_SOURCE_MANAGER",
    "HISTORY_SOURCE_SYSTEM",
    "ROLE_ADMIN",
    "ROLE_MANAGER",
    "STAGE_KIND_LOST",
    "STAGE_KIND_OPEN",
    "STAGE_KIND_WON",
    "STATUS_CLIENT",
    "STATUS_LOST",
    "STATUS_MANAGER",
    "TASK_TYPE_CALL",
    "TASK_TYPE_MEETING",
    "TASK_TYPE_MESSAGE",
    "TASK_TYPE_OTHER",
    "VALID_DEAL_STATUSES",
    "VALID_FIELD_ENTITIES",
    "VALID_HISTORY_SOURCES",
    "VALID_ROLES",
    "VALID_STAGE_KINDS",
    "VALID_TAG_ENTITIES",
    "VALID_TASK_TYPES",
]
